[package]
name = "dnd"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.16"
eframe = "0.16"
serde = { version = "1.0", features = ["derive"] }
postgres = "0.19"
r2d2 = "0.8"
r2d2_postgres = "0.18"
once_cell = "1.19"
thiserror = "1.0"
